logging:
  level: INFO

s3:
  endpointOverride: http://localhost:4569

twilio: # Twilio gateway configuration
  accountId: _
  accountToken: _
  numbers:
    - _ # First number
    - _ # Second number
  messagingServicesId:
  localDomain: _ # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: 10 # Size of push pending queue

turn: # TURN server configuration
  secret: _ # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: http://localhost:6379

messageCache: # Redis server configuration for cache cluster
  redis:
    url: http://localhost:6379

directory: # Redis server configuration for directory cluster
  url: http://localhost:6379

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://localhost:55432/postgres

attachments: # AWS S3 configuration
  accessKey: _
  accessSecret: _
  bucket: _

profiles: # AWS S3 configuration
  accessKey: _
  accessSecret: _
  bucket: _
  region: _

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: postgres
  password: admin
  url: jdbc:postgresql://localhost:5432/postgres

apn: # Apple Push Notifications configuration
  bundleId: _
  pushCertificate: _
  pushKey: _

gcm: # GCM Configuration
  senderId: 10
  apiKey: _

testDevices:
  - number: +7911202303
    code: 10020030045
